/*
 * ogengine.h — OASIS STAR API C ABI header (shared across all OASIS Omniverse games)
 *
 * This file is a copy of OGEngineClient\ogengine.h placed here for convenience.
 * The canonical source is:
 *
 *   OASIS Omniverse\OGEngineClient\ogengine.h
 *
 * The build script (BUILD_OQUAKE2RTX.bat / BUILD_OQUAKE2RTX.sh) copies the latest version
 * from OGEngineClient into this folder and into the Q2 RTX source tree automatically.
 *
 * To update manually: copy OASIS Omniverse\OGEngineClient\ogengine.h here.
 * Do NOT edit this file directly — edit the canonical source in OGEngineClient instead.
 */

/* --- Include the canonical header from OGEngineClient if building from the repo root --- */
/* If the build script has already copied it here, the file below is self-contained.       */

/**
 * OASIS WEB5 STAR API - C/C++ Wrapper for Game Integration
 * Native ABI compatible header for OGEngineClient NativeAOT exports.
 */

#ifndef OGENGINE_H
#define OGENGINE_H

/* (Full content is identical to OGEngineClient\ogengine.h — see that file for details.)       */
/* Run BUILD_OQUAKE2RTX.bat or BUILD_OQUAKE2RTX.sh to populate the Code\ folder with the real  */
/* header; this placeholder only prevents #include errors when browsing the repo directly.       */

#ifdef __cplusplus
extern "C" {
#endif

#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>

/* Stub: real declarations are in OGEngineClient\ogengine.h */
/* The build script copies that file here before compiling.  */
typedef struct { const char* base_url; const char* api_key; const char* avatar_id; int timeout_seconds; const char* client_game_source; int32_t transport; const char* oasis_dna_path; } ogengine_config_t;
typedef struct { char id[64]; char name[256]; char description[512]; char game_source[64]; char item_type[64]; char nft_id[128]; int quantity; } ogengine_item_t;
typedef struct { ogengine_item_t* items; size_t count; size_t capacity; } ogengine_item_list_t;
typedef enum { OGENGINE_SUCCESS=0, OGENGINE_ERROR_INIT_FAILED=-1, OGENGINE_ERROR_NOT_INITIALIZED=-2, OGENGINE_ERROR_NETWORK=-3, OGENGINE_ERROR_INVALID_PARAM=-4, OGENGINE_ERROR_API_ERROR=-5 } ogengine_result_t;
typedef void (*ogengine_callback_t)(ogengine_result_t result, void* user_data);
#define OGENGINE_OP_PROFILE_LOADED 0
#define OGENGINE_OP_GET_INVENTORY  3
#define OGENGINE_OP_QUESTS_CACHE_REFRESHED 28
typedef void (*ogengine_operation_callback_t)(ogengine_result_t result, int operation_type, void* user_data);

/* Core lifecycle */
ogengine_result_t ogengine_init(const ogengine_config_t* config);
void ogengine_cleanup(void);
ogengine_result_t ogengine_authenticate(const char* username, const char* password);
ogengine_result_t ogengine_authenticate_with_jwt_out(const char* username, const char* password, char* jwt_buf, size_t jwt_size);
ogengine_result_t ogengine_set_saved_session(const char* jwt);
ogengine_result_t ogengine_restore_session(void);
int ogengine_get_current_username(char* buf, size_t buf_size);
int ogengine_get_current_jwt(char* buf, size_t buf_size);
void ogengine_set_refresh_token(const char* refresh_token);
int ogengine_get_current_refresh_token(char* buf, size_t buf_size);
int ogengine_is_session_expired(void);
ogengine_result_t ogengine_set_oasis_base_url(const char* oasis_base_url);
ogengine_result_t ogengine_set_avatar_id(const char* avatar_id);

/* Inventory */
bool ogengine_has_item(const char* item_name);
ogengine_result_t ogengine_get_inventory(ogengine_item_list_t** item_list);
void ogengine_request_inventory_in_background(void);
void ogengine_invalidate_inventory_cache(void);
void ogengine_clear_cache(void);
void ogengine_free_item_list(ogengine_item_list_t* item_list);
ogengine_result_t ogengine_add_item(const char* item_name, const char* description, const char* game_source, const char* item_type, const char* nft_id, int quantity, int stack);
bool ogengine_use_item(const char* item_name, const char* context);
void ogengine_queue_add_item(const char* item_name, const char* description, const char* game_source, const char* item_type, const char* nft_id, int quantity, int stack);
#define OGENGINE_HAS_QUEUE_PICKUP_WITH_MINT 1
void ogengine_queue_pickup_with_mint(const char* item_name, const char* description, const char* game_source, const char* item_type, int do_mint, const char* provider, const char* send_to_address_after_minting, int quantity);
#define OGENGINE_HAS_QUEUE_QUEST_PROGRESS_FROM_PICKUP 1
void ogengine_queue_quest_progress_from_pickup(const char* game_source, const char* item_type, const char* item_name);
ogengine_result_t ogengine_flush_add_item_jobs(void);

/* XP / monster kill */
#define OGENGINE_HAS_QUEUE_MONSTER_KILL 1
void ogengine_queue_monster_kill(const char* monster_name, const char* game_source, int xp, int do_mint, const char* provider, const char* send_to_address, int is_boss);

/* Quests */
ogengine_result_t ogengine_get_quests(void);
ogengine_result_t ogengine_complete_quest(const char* quest_id);
void ogengine_refresh_avatar_profile(void);
ogengine_result_t ogengine_get_avatar_detail(char* buf, size_t buf_size);

/* Callbacks */
void ogengine_set_callback(ogengine_callback_t cb);
void ogengine_set_operation_callback(ogengine_operation_callback_t cb);

/* Log drain */
int  ogengine_drain_log(char* buf, size_t buf_size);
int  ogengine_drain_error(char* buf, size_t buf_size);
int  ogengine_drain_mint_result(char* buf, size_t buf_size);

/* Batch / flush */
void ogengine_flush_pending(void);

/* Cross-game event polling (ShowNarration, PlayAudio, PlayVideo, OpenWebsite, UnlockPortal) */
int  ogengine_poll_cross_game_event(char* out_json, size_t json_len);

/* Inventory grant polling */
int  ogengine_poll_inventory_grant(char* out_guid, size_t guid_len);

/* Cross-game entity spawning */
int  ogengine_poll_spawn_event(char* out_entity_id, size_t id_len, float* out_x, float* out_y, float* out_z);
void ogengine_confirm_spawn(const char* entity_id);

/* Cross-game teleportation */
int  ogengine_poll_teleport_request(char* out_map, size_t map_len, float* out_x, float* out_y, float* out_z);
void ogengine_confirm_teleport_arrival(void);
void ogengine_request_teleport(const char* target_game, const char* target_map, float x, float y, float z);

/* Portal unlock notification */
void ogengine_notify_portal_unlock(const char* portal_id);

#ifdef __cplusplus
}
#endif

#endif /* OGENGINE_H */
