<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageId>NextGenSoftware.OASIS.API.Providers.TigrisOASIS</PackageId>
    <Company>NextGen Software Ltd</Company>
    <Product>WEB4 OASIS API TigrisOASIS Provider</Product>
    <Title>WEB4 OASIS API TigrisOASIS Provider</Title>
    <Summary>Tigris Globally Distributed S3-Compatible Object Storage https://oasisomniverse.one</Summary>
    <Description>Tigris Globally Distributed S3-Compatible Object Storage Part of the OASIS HOT-Swappable Provider Architecture. https://oasisomniverse.one</Description>
    <PackageProjectUrl>https://oasisomniverse.one</PackageProjectUrl>
    <PackageIcon>OASIS.jpg</PackageIcon>
    <Authors>David Ellams (NextGen Software Ltd)</Authors>
    <PackageTags>tigris s3 distributed object storage</PackageTags>
    <PackageReleaseNotes>- Initial release. .NET 10.</PackageReleaseNotes>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/NextGenSoftwareUK/OASIS</RepositoryUrl>
    <Copyright>Copyright © NextGen Software Ltd 2019 - 2026</Copyright>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <Version>2.0.1</Version>
    <AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\..\Logos\OASIS.jpg" Pack="true" PackagePath="\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="3.7.502" />
    <ProjectReference Include="..\..\..\OASIS Architecture\NextGenSoftware.OASIS.API.Core\NextGenSoftware.OASIS.API.Core.csproj" Condition="Exists('..\..\..\OASIS Architecture\NextGenSoftware.OASIS.API.Core\NextGenSoftware.OASIS.API.Core.csproj')" />
    <PackageReference Include="NextGenSoftware.OASIS.API.Core" Version="2.0.0" Condition="!Exists('..\..\..\OASIS Architecture\NextGenSoftware.OASIS.API.Core\NextGenSoftware.OASIS.API.Core.csproj')" />
    <ProjectReference Include="..\..\..\OASIS Architecture\NextGenSoftware.OASIS.Common\NextGenSoftware.OASIS.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="README.md"><PackagePath>\</PackagePath><Pack>True</Pack></None>
  </ItemGroup>
</Project>
