import { Box, Card, CardContent, CardHeader, Chip, Grid, Typography } from '@mui/material';

// Source of truth: C:\Source\OASIS\Providers\ directory tree — 229 unique providers, 232 folder entries
// (Ceramic, Moralis, Arweave each exist in two category folders)
const providers: Record<string, { name: string; description: string }[]> = {
  'AI / Decentralised AI': [
    { name: 'Bittensor', description: 'Decentralised ML network' },
    { name: 'Galadriel', description: 'On-chain AI L1' },
    { name: 'Ritual', description: 'Decentralised AI infrastructure' },
  ],
  'Blockchain / L1 / L2 / Cross-chain': [
    { name: 'Abstract', description: 'ZK L2 (consumer crypto)' },
    { name: 'Algorand', description: 'Algorand L1' },
    { name: 'Aptos', description: 'Aptos L1' },
    { name: 'Arbitrum', description: 'Arbitrum One L2' },
    { name: 'Avalanche', description: 'Avalanche C-Chain' },
    { name: 'Axelar', description: 'Cross-chain messaging' },
    { name: 'Aztec', description: 'Private ZK rollup' },
    { name: 'BNB Chain', description: 'BNB Smart Chain' },
    { name: 'Base', description: 'Coinbase / OP Stack L2' },
    { name: 'Basechain', description: 'Loom Network EVM sidechain' },
    { name: 'Berachain', description: 'Proof-of-Liquidity L1' },
    { name: 'Bitcoin', description: 'Bitcoin L1' },
    { name: 'Cardano', description: 'Cardano L1' },
    { name: 'Ceramic / ComposeDB', description: 'Data streaming protocol' },
    { name: 'ChainLink', description: 'Decentralised oracle network' },
    { name: 'Chainflip', description: 'Native cross-chain DEX' },
    { name: 'Chainlink Functions', description: 'Serverless on-chain compute' },
    { name: 'Connext', description: 'Modular cross-chain execution' },
    { name: 'Cosmos', description: 'Cosmos Hub (IBC)' },
    { name: 'deBridge', description: 'Cross-chain liquidity protocol' },
    { name: 'EigenLayer', description: 'Restaking protocol' },
    { name: 'EOS', description: 'EOSIO / EOS L1' },
    { name: 'MultiversX (Elrond)', description: 'MultiversX L1' },
    { name: 'Espresso Systems', description: 'Decentralised sequencer' },
    { name: 'Ethereum', description: 'Ethereum mainnet + EVM' },
    { name: 'Fantom', description: 'Fantom / Sonic L1' },
    { name: 'Fhenix', description: 'FHE (Fully Homomorphic Encryption) L2' },
    { name: 'Filecoin', description: 'Decentralised storage chain' },
    { name: 'Gelato Network', description: 'Smart contract automation' },
    { name: 'Hedera Hashgraph', description: 'Hedera DLT' },
    { name: 'Hyperlane', description: 'Permissionless interoperability' },
    { name: 'LayerZero V2', description: 'Omnichain messaging' },
    { name: 'Linea', description: 'zkEVM L2 (Consensys)' },
    { name: 'Miden', description: 'Polygon Miden ZK rollup' },
    { name: 'Monad', description: 'High-performance EVM L1' },
    { name: 'Moralis', description: 'Web3 data API' },
    { name: 'NEAR', description: 'NEAR Protocol L1' },
    { name: 'OpenZeppelin Defender', description: 'Smart contract security tooling' },
    { name: 'Optimism', description: 'Optimism L2 (OP Stack)' },
    { name: 'Polkadot', description: 'Relay chain + parachains' },
    { name: 'Polygon', description: 'Polygon PoS + zkEVM' },
    { name: 'Radix', description: 'Radix DLT L1' },
    { name: 'Rootstock (RSK)', description: 'Bitcoin sidechain' },
    { name: 'Scroll', description: 'zkEVM L2' },
    { name: 'Sei Network', description: 'High-performance L1' },
    { name: 'Solana', description: 'Solana L1' },
    { name: 'Stargate', description: 'LayerZero cross-chain bridge' },
    { name: 'Starknet', description: 'ZK rollup (StarkWare)' },
    { name: 'Stacks (BlockStack)', description: 'Bitcoin L2' },
    { name: 'Stellar', description: 'Stellar L1' },
    { name: 'Sui', description: 'Sui L1' },
    { name: 'Synapse', description: 'Cross-chain bridge' },
    { name: 'TON', description: 'The Open Network L1' },
    { name: 'TRON', description: 'TRON L1' },
    { name: 'Telos', description: 'Telos EVM L1' },
    { name: 'Web3Core', description: 'Universal EVM adapter' },
    { name: 'Wormhole', description: 'Cross-chain bridge' },
    { name: 'XRP Ledger', description: 'XRP Ledger L1' },
    { name: 'Zcash', description: 'Privacy chain' },
    { name: 'zkSync', description: 'zkSync Era L2' },
  ],
  'Cloud / Edge / Serverless': [
    { name: 'AWS', description: 'Amazon Web Services' },
    { name: 'Appwrite', description: 'Open-source backend' },
    { name: 'Azure Cosmos DB', description: 'Globally-distributed NoSQL' },
    { name: 'Azure Storage', description: 'Blob / Table / Queue' },
    { name: 'Cloudflare D1', description: 'Serverless SQLite at the edge' },
    { name: 'Cloudflare Workers / KV', description: 'Edge compute + KV' },
    { name: 'Convex', description: 'Reactive backend-as-a-service' },
    { name: 'DynamoDB', description: 'Amazon managed NoSQL' },
    { name: 'Fauna', description: 'Serverless document/relational DB' },
    { name: 'Firebase', description: 'Google real-time DB + auth' },
    { name: 'Google Cloud', description: 'Google Cloud Platform' },
    { name: 'Neon', description: 'Serverless Postgres' },
    { name: 'PocketBase', description: 'Open-source BaaS' },
    { name: 'Supabase', description: 'Open-source Firebase alternative' },
    { name: 'Turso', description: 'Edge SQLite (libSQL)' },
    { name: 'Upstash', description: 'Serverless Redis + Kafka' },
  ],
  'Identity / Privacy / IP': [
    { name: 'Civic', description: 'Decentralised identity & KYC' },
    { name: 'ENS Offchain', description: 'Off-chain ENS resolver' },
    { name: 'Gitcoin Passport', description: 'Decentralised identity scoring' },
    { name: 'Holonym', description: 'ZK proof of humanity' },
    { name: 'Polygon ID', description: 'ZK decentralised identity' },
    { name: 'Privy', description: 'Embedded wallet & auth' },
    { name: 'Privy Server Wallets', description: 'Programmatic server-side wallets' },
    { name: 'Proof of Humanity', description: 'Sybil-resistance registry' },
    { name: 'Reclaim Protocol', description: 'ZK proofs of web data' },
    { name: 'Self Protocol', description: 'ZK identity verification' },
    { name: 'Sui zkLogin', description: 'Social login to blockchain' },
    { name: 'ZkSync SSO', description: 'Smart account single sign-on' },
    { name: 'zkPass', description: 'ZK data verification' },
  ],
  'Maps / Spatial / AR / Gaming': [
    { name: 'Decentraland', description: 'Decentraland metaverse' },
    { name: 'GO Map', description: 'Unity AR game framework' },
    { name: 'Google Maps', description: 'Google Maps Platform' },
    { name: 'HERE Maps', description: 'Navigation & location' },
    { name: 'MapLibre', description: 'Open-source maps' },
    { name: 'Mapbox', description: 'Mapping & geospatial' },
    { name: 'Niantic Lightship', description: 'AR platform' },
    { name: 'Ready Player Me', description: 'Cross-platform avatars' },
    { name: 'The Sandbox', description: 'Voxel gaming metaverse' },
    { name: 'WRLD 3D', description: 'Geospatial metaverse platform' },
  ],
  'Network / P2P / Web3 API': [
    { name: 'ActivityPub', description: 'Mastodon federation protocol' },
    { name: 'Akash', description: 'Decentralised cloud compute' },
    { name: 'Alchemy', description: 'Web3 developer platform' },
    { name: 'Ankr', description: 'Multi-chain RPC & staking' },
    { name: 'Arweave', description: 'Permanent on-chain storage' },
    { name: 'Blockscout', description: 'Open-source block explorer API' },
    { name: 'Celestia', description: 'Modular data availability' },
    { name: 'Ceramic / ComposeDB', description: 'Data streams' },
    { name: 'Covalent', description: 'Unified multi-chain data API' },
    { name: 'Dune Analytics', description: 'On-chain SQL queries' },
    { name: 'ENS', description: 'Ethereum Name Service' },
    { name: 'Eclipse', description: 'SVM L2 (Solana VM on Ethereum)' },
    { name: 'Goldsky', description: 'Real-time subgraph indexing' },
    { name: 'Holochain', description: 'Distributed P2P application platform' },
    { name: 'HoloWeb', description: 'Holochain browser extension' },
    { name: 'IPFS', description: 'Distributed file system' },
    { name: 'Infura', description: 'Ethereum / IPFS infrastructure' },
    { name: 'LayerZero', description: 'Omnichain messaging V1' },
    { name: 'Livepeer', description: 'Decentralised video transcoding' },
    { name: 'Moralis', description: 'Web3 data API' },
    { name: 'Moralis Streams', description: 'Real-time blockchain events' },
    { name: 'NATS JetStream', description: 'High-performance messaging' },
    { name: 'Nansen', description: 'On-chain analytics & wallet labels' },
    { name: 'Pinata', description: 'IPFS pinning service' },
    { name: 'Polybase', description: 'Decentralised database' },
    { name: 'Push Protocol', description: 'Web3 notifications (EPNS)' },
    { name: 'QuickNode', description: 'Web3 RPC infrastructure' },
    { name: 'Reservoir', description: 'NFT data & trading API' },
    { name: 'SOLID', description: 'Tim Berners-Lee personal data pods' },
    { name: 'Safe (Gnosis)', description: 'Multi-sig smart accounts' },
    { name: 'Scuttlebutt', description: 'Secure Scuttlebutt P2P protocol' },
    { name: 'SubQuery', description: 'Decentralised blockchain indexer' },
    { name: 'Tableland', description: 'Permissionless on-chain SQL' },
    { name: 'Telegram', description: 'Messaging platform' },
    { name: 'Tenderly', description: 'Smart contract dev & simulation' },
    { name: 'ThreeFold', description: 'Decentralised cloud grid' },
    { name: 'Waku', description: 'Decentralised P2P messaging' },
    { name: 'Zapper', description: 'DeFi portfolio tracker' },
  ],
  'Other / Infrastructure': [
    { name: 'Cargo', description: 'NFT minting & marketplace' },
    { name: 'Dapr', description: 'Distributed application runtime' },
    { name: 'GUN', description: 'Decentralised graph database' },
    { name: 'Intel OpenVINO', description: 'AI/ML inference toolkit' },
    { name: 'Onion Protocol (Tor)', description: 'Tor onion routing privacy' },
    { name: 'OrbitDB', description: 'Peer-to-peer database (IPFS-based)' },
    { name: 'Orion Protocol', description: 'DEX aggregator' },
    { name: 'PLAN', description: 'Collaborative community platform' },
    { name: 'SEEDS', description: 'Regenerative economy protocol' },
    { name: 'Temporal', description: 'Workflow orchestration engine' },
    { name: 'Urbit', description: 'Personal server OS & P2P network' },
  ],
  'Social / DAO / Identity': [
    { name: 'BlueSky', description: 'AT Protocol decentralised social' },
    { name: 'Discord', description: 'Community & gaming platform' },
    { name: 'Farcaster', description: 'Decentralised social protocol' },
    { name: 'Lens Protocol V1', description: 'Social graph (V1)' },
    { name: 'Lens Protocol V2', description: 'Social graph (V2)' },
    { name: 'Lit Protocol', description: 'Threshold cryptography & access control' },
    { name: 'Loom', description: 'Video messaging' },
    { name: 'Matrix', description: 'Decentralised real-time messaging' },
    { name: 'Nostr', description: 'Censorship-resistant social protocol' },
    { name: 'Story Protocol', description: 'Programmable IP licensing' },
    { name: 'The Graph', description: 'Decentralised GraphQL indexing' },
    { name: 'World ID', description: 'Worldcoin ZK proof-of-personhood' },
  ],
  'Storage / Database': [
    { name: 'Algolia', description: 'Hosted search-as-a-service' },
    { name: 'ArangoDB', description: 'Multi-model (graph/doc/KV)' },
    { name: 'ArcadeDB', description: 'Multi-model (graph/doc/KV/time-series)' },
    { name: 'Arweave', description: 'Permanent on-chain storage' },
    { name: 'BigQuery', description: 'Serverless analytics' },
    { name: 'Cassandra', description: 'Wide-column distributed DB' },
    { name: 'Chroma', description: 'AI-native open-source vector DB' },
    { name: 'ClickHouse', description: 'Columnar OLAP analytics' },
    { name: 'Cloudinary', description: 'Cloud media management' },
    { name: 'CockroachDB', description: 'Distributed SQL' },
    { name: 'CouchDB', description: 'Document database' },
    { name: 'Couchbase', description: 'NoSQL + full-text search' },
    { name: 'Databricks', description: 'Unified data + AI platform' },
    { name: 'Deno Deploy', description: 'Edge serverless functions' },
    { name: 'Dragonfly', description: 'High-performance Redis-compatible cache' },
    { name: 'Apache Druid', description: 'Real-time analytics OLAP' },
    { name: 'DuckDB', description: 'In-process analytical SQL' },
    { name: 'Elasticsearch', description: 'Distributed search & analytics' },
    { name: 'Fastly', description: 'CDN edge compute & KV' },
    { name: 'Fly.io', description: 'Globally distributed app platform' },
    { name: 'Garnet', description: 'Microsoft Redis-compatible cache' },
    { name: 'InfluxDB', description: 'Purpose-built time-series DB' },
    { name: 'KeyDB', description: 'Multi-threaded Redis fork' },
    { name: 'LanceDB', description: 'Multimodal AI vector database' },
    { name: 'Litestream', description: 'SQLite continuous replication' },
    { name: 'Local File', description: 'Local filesystem storage' },
    { name: 'Marqo', description: 'Tensor search & vector DB' },
    { name: 'Meilisearch', description: 'Fast open-source search' },
    { name: 'Memcached', description: 'Distributed memory cache' },
    { name: 'Milvus', description: 'Open-source vector database' },
    { name: 'MinIO', description: 'S3-compatible object storage' },
    { name: 'MongoDB', description: 'Document database' },
    { name: 'MotherDuck', description: 'Serverless DuckDB in the cloud' },
    { name: 'Neo4j', description: 'Graph database' },
    { name: 'Neo4j Aura', description: 'Managed cloud graph DB' },
    { name: 'Netlify Blobs', description: 'Edge object storage' },
    { name: 'Nile', description: 'Serverless multi-tenant Postgres' },
    { name: 'OpenSearch', description: 'Elasticsearch fork' },
    { name: 'Oracle DB', description: 'Oracle Database' },
    { name: 'pgvector', description: 'Postgres vector extension' },
    { name: 'Pinecone', description: 'Managed vector database' },
    { name: 'Apache Pinot', description: 'Real-time OLAP' },
    { name: 'PlanetScale', description: 'Serverless MySQL' },
    { name: 'PostgreSQL', description: 'Relational database' },
    { name: 'PouchDB', description: 'Browser/offline CouchDB sync' },
    { name: 'Qdrant', description: 'High-performance vector search' },
    { name: 'QuestDB', description: 'High-performance time-series SQL' },
    { name: 'RavenDB', description: '.NET-native document database' },
    { name: 'Redis', description: 'In-memory data structure store' },
    { name: 'Redshift', description: 'Amazon cloud data warehouse' },
    { name: 'SQLite', description: 'Embedded relational database' },
    { name: 'SQL Server', description: 'Microsoft SQL Server' },
    { name: 'ScyllaDB', description: 'C++ Cassandra-compatible DB' },
    { name: 'Snowflake', description: 'Cloud data warehouse' },
    { name: 'Solr', description: 'Enterprise search' },
    { name: 'SurrealDB', description: 'Multi-model cloud-native DB' },
    { name: 'Tigris', description: 'Globally distributed S3-compatible' },
    { name: 'TimescaleDB', description: 'Time-series Postgres extension' },
    { name: 'Typesense', description: 'Typo-tolerant open-source search' },
    { name: 'ValKey', description: 'Linux Foundation Redis fork' },
    { name: 'Vercel KV', description: 'Edge key-value (Upstash Redis)' },
    { name: 'Weaviate', description: 'Open-source vector database' },
    { name: 'Xata', description: 'Serverless Postgres + search' },
    { name: 'Zilliz', description: 'Managed Milvus vector DB' },
  ],
};

// Count unique names (Ceramic, Moralis, Arweave appear in two categories each)
const allNames = new Set(Object.values(providers).flatMap(arr => arr.map(p => p.name)));
const total = allNames.size;

const categoryIcons: Record<string, string> = {
  'AI / Decentralised AI': '🤖',
  'Blockchain / L1 / L2 / Cross-chain': '⛓️',
  'Cloud / Edge / Serverless': '☁️',
  'Identity / Privacy / IP': '🔐',
  'Maps / Spatial / AR / Gaming': '🗺️',
  'Network / P2P / Web3 API': '🌐',
  'Other / Infrastructure': '🏗️',
  'Social / DAO / Identity': '💬',
  'Storage / Database': '🗄️',
};

export default function Providers() {
  return (
    <Grid container spacing={3}>
      <Grid item xs={12}>
        <Box display="flex" alignItems="center" gap={2} flexWrap="wrap">
          <Typography variant="h4">Supported Providers</Typography>
          <Chip label={`${total} providers`} color="primary" size="medium" />
        </Box>
        <Typography variant="body2" color="text.secondary" sx={{ mt: 1 }}>
          All providers are fully implemented and hot-swappable via OASIS HyperDrive. Three providers
          (Ceramic, Moralis, Arweave) span two categories each — they are counted once.
        </Typography>
      </Grid>
      {Object.entries(providers).map(([group, items]) => (
        <Grid item xs={12} md={6} key={group}>
          <Card>
            <CardHeader
              title={`${categoryIcons[group] ?? ''} ${group}`}
              subheader={`${items.length} entries`}
            />
            <CardContent>
              <Typography color="text.secondary" variant="body2">
                {items.map(p => p.name).join(' • ')}
              </Typography>
            </CardContent>
          </Card>
        </Grid>
      ))}
    </Grid>
  );
}
