using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using NextGenSoftware.OASIS.API.Core.Enums;
using NextGenSoftware.OASIS.API.Core.Holons;
using NextGenSoftware.OASIS.API.Core.Interfaces;
using NextGenSoftware.OASIS.API.DNA;
using NextGenSoftware.OASIS.API.ONODE.Core.Managers;
using NextGenSoftware.OASIS.Common;
using NextGenSoftware.OASIS.Web6.Core.Models;

namespace NextGenSoftware.OASIS.Web6.Core.Managers
{
    /// <summary>
    /// Manages the Holonic BRAID shared reasoning-graph library (whitepaper §3). The library is itself a holon
    /// (HolonicBraidLibrary) - its children are individual graph holons (HolonicBraidGraph), one per task type τ.
    /// Every Mermaid reasoning graph generated by any agent, for any task type, is stored once and re-used by every
    /// future agent/session that hits the same task type - so PPD (performance-per-dollar) gains compound globally
    /// instead of resetting per agent/instance. Graphs are saved through the OASIS COSMIC ORM, so they automatically
    /// replicate/fail-over across whichever providers (MongoDB for fast access, Solana for immutable on-chain
    /// provenance, IPFS for decentralised permanence, etc.) are configured for auto-replication in OASIS_DNA.json -
    /// the same holon Id resolves to the same graph from any backend (ProviderUniqueStorageKey, per provider).
    /// </summary>
    public class HolonicBraidManager : OASISManager
    {
        // The shared graph library is a global singleton holon - every Holonic BRAID deployment shares the same well-known id.
        public static readonly Guid LibraryHolonId = new Guid("00000000-0000-0000-0000-0000000B6A1D");

        /// <summary>If a graph's average solver accuracy drops below this threshold, the Generator is reinvoked to produce an improved replacement.</summary>
        public double AccuracyRegenerationThreshold { get; set; } = 0.85;

        public HolonicBraidManager(Guid avatarId, OASISDNA OASISDNA = null) : base(avatarId, OASISDNA) { }

        public HolonicBraidManager(IOASISStorageProvider OASISStorageProvider, Guid avatarId, OASISDNA OASISDNA = null)
            : base(OASISStorageProvider, avatarId, OASISDNA) { }

        /// <summary>Gets the single shared library holon, creating it if this is the very first call anywhere.</summary>
        public async Task<OASISResult<bool>> EnsureLibraryHolonAsync()
        {
            OASISResult<bool> result = new OASISResult<bool>();
            OASISResult<IHolon> loadResult = await Data.LoadHolonAsync(LibraryHolonId, false);

            if (!loadResult.IsError && loadResult.Result != null)
            {
                result.Result = true;
                return result;
            }

            Holon holon = new Holon(LibraryHolonId)
            {
                Name = "HolonicBraidLibrary",
                Description = "The shared Holonic BRAID reasoning-graph library. Children are individual graph holons, one per task type."
            };
            holon.HolonType = HolonType.HolonicBraidLibrary;

            OASISResult<IHolon> saveResult = await Data.SaveHolonAsync(holon, AvatarId, false);
            result.Result = !saveResult.IsError;
            return result;
        }

        /// <summary>
        /// The lookup-or-create entry point: finds an existing reasoning graph for the given task type in the shared
        /// library. Returns null if none exists yet (the caller's generator agent should then create one and call
        /// SaveGraphAsync). Every successful lookup is at zero generation cost - this is what sustains BRAID's PPD
        /// gains at platform scale instead of collapsing as task volume grows (whitepaper §2.4).
        /// </summary>
        public async Task<OASISResult<HolonicBraidGraphDto>> FindGraphForTaskTypeAsync(string taskType)
        {
            OASISResult<HolonicBraidGraphDto> result = new OASISResult<HolonicBraidGraphDto>();

            OASISResult<IEnumerable<IHolon>> loadResult = await Data.LoadAllHolonsAsync(HolonType.HolonicBraidGraph);

            if (loadResult.IsError)
            {
                OASISErrorHandling.HandleError(ref result, $"Error loading HolonicBraidGraph holons. Reason: {loadResult.Message}");
                return result;
            }

            List<IHolon> matches = loadResult.Result?.Where(h =>
                h.MetaData != null &&
                h.MetaData.TryGetValue("TaskType", out object mdTaskType) &&
                string.Equals(mdTaskType?.ToString(), taskType, StringComparison.OrdinalIgnoreCase)).ToList() ?? new List<IHolon>();

            if (matches.Count == 0)
            {
                result.Result = null;
                return result;
            }

            // Conflict resolution: if two agents independently generated graphs for the same task type, keep the
            // superior one (by accuracy then reuse count) and let the others retire (whitepaper §3.2, conflict resolution row).
            IHolon match = matches.Count == 1 ? matches[0] : ResolveConflict(matches);
            HolonicBraidGraphDto dto = MapToDto(match);

            // Accuracy-threshold regeneration: flag (but still return) graphs whose accuracy has degraded - the
            // caller's generator agent should produce a replacement and call SaveGraphAsync to version it forward.
            if (dto.AvgSolverAccuracy < AccuracyRegenerationThreshold)
                dto.MermaidDiagram += $"\n%% ACCURACY_BELOW_THRESHOLD: {dto.AvgSolverAccuracy:F2} < {AccuracyRegenerationThreshold:F2} - regeneration recommended";

            // Bump the reuse counter - every future agent that retrieves this graph gets it at zero generation cost.
            dto.TimesReused++;
            match.MetaData["TimesReused"] = dto.TimesReused;
            await Data.SaveHolonAsync(match, AvatarId, false);

            result.Result = dto;
            return result;
        }

        private static IHolon ResolveConflict(List<IHolon> candidates)
        {
            return candidates
                .OrderByDescending(h => h.MetaData.TryGetValue("AvgSolverAccuracy", out object a) && double.TryParse(a?.ToString(), out double acc) ? acc : 1.0)
                .ThenByDescending(h => h.MetaData.TryGetValue("TimesReused", out object r) && int.TryParse(r?.ToString(), out int reused) ? reused : 0)
                .First();
        }

        /// <summary>
        /// Stores a newly generated reasoning graph as a child of the shared library holon (called once per task type
        /// by the generator agent, or to publish a new version when regenerating a degraded/conflicting graph).
        /// </summary>
        public async Task<OASISResult<HolonicBraidGraphDto>> SaveGraphAsync(string taskType, string mermaidDiagram, string generatedByModel, int version = 1)
        {
            OASISResult<HolonicBraidGraphDto> result = new OASISResult<HolonicBraidGraphDto>();
            await EnsureLibraryHolonAsync();

            Holon holon = new Holon(HolonType.HolonicBraidGraph)
            {
                Name = $"BraidGraph-{taskType}-v{version}",
                Description = $"Holonic BRAID reasoning graph for task type '{taskType}', generated by {generatedByModel}."
            };

            holon.MetaData["TaskType"] = taskType;
            holon.MetaData["ParentHolonId"] = LibraryHolonId.ToString();
            holon.MetaData["MermaidDiagram"] = mermaidDiagram;
            holon.MetaData["GeneratedByModel"] = generatedByModel;
            holon.MetaData["TimesReused"] = 0;
            holon.MetaData["AvgSolverAccuracy"] = 1.0;
            holon.MetaData["Version"] = version;
            holon.MetaData["CreatedUtc"] = DateTime.UtcNow.ToString("o");

            OASISResult<IHolon> saveResult = await Data.SaveHolonAsync(holon, AvatarId, false);

            if (saveResult.IsError || saveResult.Result == null)
            {
                OASISErrorHandling.HandleError(ref result, $"Error saving HolonicBraidGraph holon. Reason: {saveResult.Message}");
                return result;
            }

            result.Result = MapToDto(saveResult.Result);
            return result;
        }

        /// <summary>
        /// Feeds a real solver outcome back into a graph's quality metadata via EMA, so the library's accuracy
        /// tracking stays current (whitepaper §3.1 - "usage_count, avg_solver_accuracy" accumulate over time).
        /// </summary>
        public async Task<OASISResult<bool>> RecordSolverOutcomeAsync(Guid graphHolonId, bool wasAccurate, double emaAlpha = 0.2)
        {
            OASISResult<bool> result = new OASISResult<bool>();
            OASISResult<IHolon> loadResult = await Data.LoadHolonAsync(graphHolonId, false);

            if (loadResult.IsError || loadResult.Result == null)
            {
                OASISErrorHandling.HandleError(ref result, $"Graph holon {graphHolonId} not found.");
                return result;
            }

            double previous = loadResult.Result.MetaData.TryGetValue("AvgSolverAccuracy", out object a) && double.TryParse(a?.ToString(), out double acc) ? acc : 1.0;
            double sample = wasAccurate ? 1.0 : 0.0;
            loadResult.Result.MetaData["AvgSolverAccuracy"] = (emaAlpha * sample) + ((1 - emaAlpha) * previous);

            OASISResult<IHolon> saveResult = await Data.SaveHolonAsync(loadResult.Result, AvatarId, false);
            result.Result = !saveResult.IsError;
            return result;
        }

        private static HolonicBraidGraphDto MapToDto(IHolon holon)
        {
            return new HolonicBraidGraphDto
            {
                Id = holon.Id,
                ParentHolonId = holon.MetaData.TryGetValue("ParentHolonId", out object p) && Guid.TryParse(p?.ToString(), out Guid pid) ? pid : Guid.Empty,
                TaskType = holon.MetaData.TryGetValue("TaskType", out object t) ? t?.ToString() : null,
                MermaidDiagram = holon.MetaData.TryGetValue("MermaidDiagram", out object m) ? m?.ToString() : null,
                GeneratedByModel = holon.MetaData.TryGetValue("GeneratedByModel", out object g) ? g?.ToString() : null,
                TimesReused = holon.MetaData.TryGetValue("TimesReused", out object r) && r != null ? Convert.ToInt32(r) : 0,
                AvgSolverAccuracy = holon.MetaData.TryGetValue("AvgSolverAccuracy", out object acc) && acc != null && double.TryParse(acc.ToString(), out double accVal) ? accVal : 1.0,
                Version = holon.MetaData.TryGetValue("Version", out object v) && v != null ? Convert.ToInt32(v) : 1,
                CreatedUtc = holon.MetaData.TryGetValue("CreatedUtc", out object c) && c != null && DateTime.TryParse(c.ToString(), out DateTime dt) ? dt : DateTime.UtcNow
            };
        }
    }
}
