// SPDX-License-Identifier: UNLICENSED
// compiler version must be greater than or equal to 0.8.3 and less than 0.9.0
pragma solidity ^0.8.9;

enum ProviderType {
    SolanaOASIS,
    RadixOASIS,
    HoloOASIS,
    EthereumOASIS,
    EOSIOOASIS,
    TelosOASIS,
    SEEDSOASIS,
    LoomOASIS,
    TONOASIS,
    StellarOASIS,
    BlockStackOASIS,
    HashgraphOASIS,
    SOLIDOASIS,
    IPFSOASIS,
    PinataOASIS,
    ActivityPubOASIS,
    ScuttlebuttOASIS,
    MongoDBOASIS,
    SQLLiteDBOASIS,
    SQLServerDBOASIS,
    OracleDBOASIS,
    AzureStorageOASIS,
    AzureCosmosDBOASIS,
    ElrondOASIS,
    UrbitOASIS,
    ChainLinkOASIS,
    ThreeFoldOASIS,
    PLANOASIS,
    HoloWebOASIS,
    TRONOASIS,
    Neo4jOASIS,
    All,
    None,
    Default
}
