/*
 * ogengine_sync.h — OASIS STAR API async sync layer (shared across all OASIS Omniverse games)
 *
 * This file is a copy of OGEngineClient\ogengine_sync.h placed here for convenience.
 * The canonical source is:
 *
 *   OASIS Omniverse\OGEngineClient\ogengine_sync.h
 *
 * The build script (BUILD_OQUAKE2.bat / BUILD_OQUAKE2.sh) copies the latest version
 * from OGEngineClient into Code\ and into the Yamagi Q2 source tree automatically.
 *
 * To update manually: copy OASIS Omniverse\OGEngineClient\ogengine_sync.h here.
 * Do NOT edit this file directly — edit the canonical source in OGEngineClient instead.
 */

#ifndef STAR_SYNC_H
#define STAR_SYNC_H

#include "ogengine.h"
#include <stddef.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef void (*ogengine_sync_add_item_log_fn)(const char* item_name, int success, const char* error_message, void* user_data);
void ogengine_sync_set_add_item_log_cb(ogengine_sync_add_item_log_fn cb, void* user_data);
void ogengine_sync_init(void);
void ogengine_sync_cleanup(void);
void ogengine_sync_pump(void);

typedef struct ogengine_sync_local_item {
    char name[256];
    char description[512];
    char game_source[64];
    char item_type[64];
    char nft_id[128];
    int  quantity;
    int  stack;
    int  synced;
} ogengine_sync_local_item_t;

/* Auth */
void ogengine_sync_auth_start(const char* username, const char* password,
                              void (*on_done)(void*), void* user_data);
int  ogengine_sync_auth_in_progress(void);
int  ogengine_sync_auth_get_result(int* out_success, char* out_err, size_t err_size);

/* Inventory */
void ogengine_sync_inventory_start(ogengine_sync_local_item_t* items, int count,
                                   void (*on_done)(void*), void* user_data);
int  ogengine_sync_inventory_in_progress(void);
int  ogengine_sync_inventory_get_result(int* out_synced, char* out_err, size_t err_size);

/* Send item */
void ogengine_sync_send_item_start(const char* target, const char* item_name, int quantity,
                                   int is_clan, const char* item_id,
                                   void (*on_done)(void*), void* user_data);
int  ogengine_sync_send_item_in_progress(void);
int  ogengine_sync_send_item_get_result(int* out_success, char* out_err, size_t err_size);

/* Use item */
void ogengine_sync_use_item_start(const char* item_name, const char* context,
                                  void (*on_done)(void*), void* user_data);
int  ogengine_sync_use_item_in_progress(void);
int  ogengine_sync_use_item_get_result(int* out_success, char* out_err, size_t err_size);

#ifdef __cplusplus
}
#endif

#endif /* STAR_SYNC_H */
