import { FeaturedAsset } from "@/types/rwa/rwa.type";
import { CombinedRwa } from "@/types/rwa/rwa.type";

// Placeholder images from Unsplash (real estate)
const PLACEHOLDER_IMAGES = [
  "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
  "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
  "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
  "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop", // Modern modular home
  "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
  "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop",
  "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
  "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&h=600&fit=crop",
];

export const MOCK_FEATURED_ASSETS: FeaturedAsset[] = [
  {
    id: "1",
    tokenId: "1",
    title: "Luxury Beverly Hills Estate",
    location: "Beverly Hills, CA",
    price: 1890000,
    priceCurrency: "USD",
    image: PLACEHOLDER_IMAGES[0],
    images: [PLACEHOLDER_IMAGES[0]],
    keySpecs: {
      propertyType: "Residential",
    },
    assetType: "Real Estate",
    yield: 7.48,
    link: "/rwa/1",
    geolocation: {
      latitude: 34.0736,
      longitude: -118.4004,
    },
  },
  {
    id: "2",
    tokenId: "2",
    title: "Modern Downtown Loft",
    location: "Manhattan, NY",
    price: 2450000,
    priceCurrency: "USD",
    image: PLACEHOLDER_IMAGES[1],
    images: [PLACEHOLDER_IMAGES[1]],
    keySpecs: {
      bedrooms: 3,
      bathrooms: 2,
      squareFeet: 2200,
      propertyType: "Residential",
    },
    assetType: "Real Estate",
    yield: 6.2,
    link: "/rwa/2",
    geolocation: {
      latitude: 40.7128,
      longitude: -74.0060,
    },
  },
  {
    id: "3",
    tokenId: "3",
    title: "Coastal Beachfront Property",
    location: "Malibu, CA",
    price: 3200000,
    priceCurrency: "USD",
    image: PLACEHOLDER_IMAGES[2],
    images: [PLACEHOLDER_IMAGES[2]],
    keySpecs: {
      bedrooms: 6,
      bathrooms: 5,
      squareFeet: 4200,
      lotSize: 12000,
      propertyType: "Residential",
    },
    assetType: "Real Estate",
    yield: 8.1,
    link: "/rwa/3",
    geolocation: {
      latitude: 34.0259,
      longitude: -118.7798,
    },
  },
  {
    id: "4",
    tokenId: "4",
    title: "Modern Modular Home",
    location: "Austin, TX",
    price: 1650000,
    priceCurrency: "USD",
    image: PLACEHOLDER_IMAGES[3],
    images: [PLACEHOLDER_IMAGES[3]],
    keySpecs: {
      bedrooms: 4,
      bathrooms: 3,
      squareFeet: 2800,
      propertyType: "Residential",
    },
    assetType: "Real Estate",
    yield: 5.8,
    link: "/rwa/4",
    geolocation: {
      latitude: 30.2672,
      longitude: -97.7431,
    },
  },
  {
    id: "5",
    tokenId: "5",
    title: "Mountain View Estate",
    location: "Aspen, CO",
    price: 4500000,
    priceCurrency: "USD",
    image: PLACEHOLDER_IMAGES[4],
    images: [PLACEHOLDER_IMAGES[4]],
    keySpecs: {
      bedrooms: 7,
      bathrooms: 6,
      squareFeet: 5800,
      lotSize: 25000,
      propertyType: "Residential",
    },
    assetType: "Real Estate",
    yield: 9.2,
    link: "/rwa/5",
    geolocation: {
      latitude: 39.1911,
      longitude: -106.8175,
    },
  },
];

export const MOCK_RWA_ASSETS: CombinedRwa[] = [
  {
    tokenId: "1",
    title: "Luxury Beverly Hills Estate",
    assetDescription: "Stunning Mediterranean-style estate with panoramic city views, private pool, and guest house. Recently renovated with high-end finishes throughout.",
    proofOfOwnershipDocument: "ipfs://QmExample1",
    uniqueIdentifier: "BH-2024-001",
    royalty: 7.48,
    price: 1890000,
    network: "Solana",
    image: PLACEHOLDER_IMAGES[0],
    ownerContact: "owner@example.com",
    assetType: "Real Estate",
    insuranceStatus: "Active",
    geolocation: {
      latitude: 34.0736,
      longitude: -118.4004,
    },
    valuationDate: "2024-09-15",
    propertyType: "Residential",
    area: 3500,
    constructionYear: 1985,
    metadata: "ipfs://QmMetadata1",
    mintAccount: "mint1",
    transactionHash: "tx1",
    version: 1,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: null,
    ownerEmail: "owner@example.com",
    ownerUsername: "property_owner_1",
    oldPrice: 1750000,
    newPrice: 1890000,
    changedAt: "2024-12-01T10:00:00Z",
  },
  {
    tokenId: "2",
    title: "Modern Downtown Loft",
    assetDescription: "Sleek contemporary loft in the heart of Manhattan with floor-to-ceiling windows, high ceilings, and modern amenities.",
    proofOfOwnershipDocument: "ipfs://QmExample2",
    uniqueIdentifier: "NYC-2024-002",
    royalty: 6.2,
    price: 2450000,
    network: "Solana",
    image: PLACEHOLDER_IMAGES[1],
    ownerContact: "owner2@example.com",
    assetType: "Real Estate",
    insuranceStatus: "Active",
    geolocation: {
      latitude: 40.7128,
      longitude: -74.0060,
    },
    valuationDate: "2024-08-20",
    propertyType: "Residential",
    area: 2200,
    constructionYear: 2015,
    metadata: "ipfs://QmMetadata2",
    mintAccount: "mint2",
    transactionHash: "tx2",
    version: 1,
    createdAt: "2024-02-10T10:00:00Z",
    updatedAt: null,
    ownerEmail: "owner2@example.com",
    ownerUsername: "property_owner_2",
    oldPrice: 2300000,
    newPrice: 2450000,
    changedAt: "2024-11-15T10:00:00Z",
  },
  {
    tokenId: "3",
    title: "Coastal Beachfront Property",
    assetDescription: "Exclusive beachfront estate with direct ocean access, infinity pool, and world-class amenities. Perfect for luxury living or vacation rental.",
    proofOfOwnershipDocument: "ipfs://QmExample3",
    uniqueIdentifier: "MAL-2024-003",
    royalty: 8.1,
    price: 3200000,
    network: "Solana",
    image: PLACEHOLDER_IMAGES[2],
    ownerContact: "owner3@example.com",
    assetType: "Real Estate",
    insuranceStatus: "Active",
    geolocation: {
      latitude: 34.0259,
      longitude: -118.7798,
    },
    valuationDate: "2024-10-01",
    propertyType: "Residential",
    area: 4200,
    constructionYear: 2010,
    metadata: "ipfs://QmMetadata3",
    mintAccount: "mint3",
    transactionHash: "tx3",
    version: 1,
    createdAt: "2024-03-05T10:00:00Z",
    updatedAt: null,
    ownerEmail: "owner3@example.com",
    ownerUsername: "property_owner_3",
    oldPrice: 3100000,
    newPrice: 3200000,
    changedAt: "2024-12-10T10:00:00Z",
  },
  {
    tokenId: "4",
    title: "Modern Modular Home",
    assetDescription: "Contemporary modular home featuring energy-efficient design, modern finishes, and sustainable construction. Quick assembly and customizable floor plans.",
    proofOfOwnershipDocument: "ipfs://QmExample4",
    uniqueIdentifier: "AUS-2024-004",
    royalty: 5.8,
    price: 1650000,
    network: "Solana",
    image: PLACEHOLDER_IMAGES[3],
    ownerContact: "owner4@example.com",
    assetType: "Real Estate",
    insuranceStatus: "Active",
    geolocation: {
      latitude: 30.2672,
      longitude: -97.7431,
    },
    valuationDate: "2024-07-15",
    propertyType: "Residential",
    area: 2800,
    constructionYear: 2023,
    metadata: "ipfs://QmMetadata4",
    mintAccount: "mint4",
    transactionHash: "tx4",
    version: 1,
    createdAt: "2024-04-20T10:00:00Z",
    updatedAt: null,
    ownerEmail: "owner4@example.com",
    ownerUsername: "property_owner_4",
    oldPrice: 1600000,
    newPrice: 1650000,
    changedAt: "2024-11-01T10:00:00Z",
  },
  {
    tokenId: "5",
    title: "Mountain View Estate",
    assetDescription: "Luxury mountain estate with ski-in/ski-out access, private hot tub, and breathtaking mountain views. Perfect for year-round living.",
    proofOfOwnershipDocument: "ipfs://QmExample5",
    uniqueIdentifier: "ASP-2024-005",
    royalty: 9.2,
    price: 4500000,
    network: "Solana",
    image: PLACEHOLDER_IMAGES[4],
    ownerContact: "owner5@example.com",
    assetType: "Real Estate",
    insuranceStatus: "Active",
    geolocation: {
      latitude: 39.1911,
      longitude: -106.8175,
    },
    valuationDate: "2024-09-30",
    propertyType: "Residential",
    area: 5800,
    constructionYear: 2005,
    metadata: "ipfs://QmMetadata5",
    mintAccount: "mint5",
    transactionHash: "tx5",
    version: 1,
    createdAt: "2024-05-10T10:00:00Z",
    updatedAt: null,
    ownerEmail: "owner5@example.com",
    ownerUsername: "property_owner_5",
    oldPrice: 4400000,
    newPrice: 4500000,
    changedAt: "2024-12-05T10:00:00Z",
  },
  {
    tokenId: "6",
    title: "Urban Penthouse",
    assetDescription: "Stunning penthouse with 360-degree city views, private rooftop terrace, and premium finishes throughout.",
    proofOfOwnershipDocument: "ipfs://QmExample6",
    uniqueIdentifier: "SF-2024-006",
    royalty: 6.5,
    price: 2800000,
    network: "Solana",
    image: PLACEHOLDER_IMAGES[5],
    ownerContact: "owner6@example.com",
    assetType: "Real Estate",
    insuranceStatus: "Active",
    geolocation: {
      latitude: 37.7749,
      longitude: -122.4194,
    },
    valuationDate: "2024-08-10",
    propertyType: "Residential",
    area: 3100,
    constructionYear: 2018,
    metadata: "ipfs://QmMetadata6",
    mintAccount: "mint6",
    transactionHash: "tx6",
    version: 1,
    createdAt: "2024-06-15T10:00:00Z",
    updatedAt: null,
    ownerEmail: "owner6@example.com",
    ownerUsername: "property_owner_6",
    oldPrice: 2750000,
    newPrice: 2800000,
    changedAt: "2024-11-20T10:00:00Z",
  },
  {
    tokenId: "7",
    title: "Countryside Villa",
    assetDescription: "Elegant countryside villa with extensive grounds, pool, tennis court, and guest accommodations.",
    proofOfOwnershipDocument: "ipfs://QmExample7",
    uniqueIdentifier: "CT-2024-007",
    royalty: 7.0,
    price: 2200000,
    network: "Solana",
    image: PLACEHOLDER_IMAGES[6],
    ownerContact: "owner7@example.com",
    assetType: "Real Estate",
    insuranceStatus: "Active",
    geolocation: {
      latitude: 41.3083,
      longitude: -72.9279,
    },
    valuationDate: "2024-07-01",
    propertyType: "Residential",
    area: 4500,
    constructionYear: 2000,
    metadata: "ipfs://QmMetadata7",
    mintAccount: "mint7",
    transactionHash: "tx7",
    version: 1,
    createdAt: "2024-07-01T10:00:00Z",
    updatedAt: null,
    ownerEmail: "owner7@example.com",
    ownerUsername: "property_owner_7",
    oldPrice: 2150000,
    newPrice: 2200000,
    changedAt: "2024-10-15T10:00:00Z",
  },
  {
    tokenId: "8",
    title: "Luxury Waterfront Condo",
    assetDescription: "Modern waterfront condominium with marina access, private balcony, and resort-style amenities.",
    proofOfOwnershipDocument: "ipfs://QmExample8",
    uniqueIdentifier: "FL-2024-008",
    royalty: 5.5,
    price: 1950000,
    network: "Solana",
    image: PLACEHOLDER_IMAGES[7],
    ownerContact: "owner8@example.com",
    assetType: "Real Estate",
    insuranceStatus: "Active",
    geolocation: {
      latitude: 25.7617,
      longitude: -80.1918,
    },
    valuationDate: "2024-06-20",
    propertyType: "Residential",
    area: 2400,
    constructionYear: 2012,
    metadata: "ipfs://QmMetadata8",
    mintAccount: "mint8",
    transactionHash: "tx8",
    version: 1,
    createdAt: "2024-08-10T10:00:00Z",
    updatedAt: null,
    ownerEmail: "owner8@example.com",
    ownerUsername: "property_owner_8",
    oldPrice: 1900000,
    newPrice: 1950000,
    changedAt: "2024-11-10T10:00:00Z",
  },
];

