import type { ChainObserverData } from "@/types/chains";
import type { PriceFeed } from "@/types/price-feed";

/**
 * Mock data for development
 * This will be replaced with real API calls
 */

export const mockPriceFeeds: PriceFeed[] = [
  {
    token: "SOL",
    price: 142.35,
    change24h: 2.3,
    deviation: 0.12,
    activeSources: 8,
    totalSources: 12,
    lastUpdate: new Date(Date.now() - 5000),
    sources: [],
    confidence: 95,
  },
  {
    token: "ETH",
    price: 3421.12,
    change24h: 1.1,
    deviation: 0.08,
    activeSources: 12,
    totalSources: 12,
    lastUpdate: new Date(Date.now() - 3000),
    sources: [],
    confidence: 99,
  },
  {
    token: "BTC",
    price: 67234.56,
    change24h: 3.8,
    deviation: 0.05,
    activeSources: 12,
    totalSources: 12,
    lastUpdate: new Date(Date.now() - 2000),
    sources: [],
    confidence: 99,
  },
  {
    token: "XRD",
    price: 0.0542,
    change24h: -0.5,
    deviation: 0.15,
    activeSources: 6,
    totalSources: 12,
    lastUpdate: new Date(Date.now() - 8000),
    sources: [],
    confidence: 85,
  },
  {
    token: "MATIC",
    price: 0.8234,
    change24h: 0.8,
    deviation: 0.10,
    activeSources: 10,
    totalSources: 12,
    lastUpdate: new Date(Date.now() - 4000),
    sources: [],
    confidence: 92,
  },
  {
    token: "ARB",
    price: 1.2341,
    change24h: 3.2,
    deviation: 0.18,
    activeSources: 9,
    totalSources: 12,
    lastUpdate: new Date(Date.now() - 6000),
    sources: [],
    confidence: 88,
  },
  {
    token: "AVAX",
    price: 34.56,
    change24h: 1.5,
    deviation: 0.11,
    activeSources: 11,
    totalSources: 12,
    lastUpdate: new Date(Date.now() - 7000),
    sources: [],
    confidence: 91,
  },
  {
    token: "OP",
    price: 2.1234,
    change24h: 2.1,
    deviation: 0.13,
    activeSources: 9,
    totalSources: 12,
    lastUpdate: new Date(Date.now() - 5500),
    sources: [],
    confidence: 89,
  },
  {
    token: "FTM",
    price: 0.4567,
    change24h: -1.2,
    deviation: 0.16,
    activeSources: 8,
    totalSources: 12,
    lastUpdate: new Date(Date.now() - 9000),
    sources: [],
    confidence: 86,
  },
  {
    token: "BNB",
    price: 312.45,
    change24h: 0.9,
    deviation: 0.09,
    activeSources: 11,
    totalSources: 12,
    lastUpdate: new Date(Date.now() - 3500),
    sources: [],
    confidence: 93,
  },
  {
    token: "ADA",
    price: 0.5678,
    change24h: 1.7,
    deviation: 0.12,
    activeSources: 10,
    totalSources: 12,
    lastUpdate: new Date(Date.now() - 4500),
    sources: [],
    confidence: 90,
  },
  {
    token: "DOT",
    price: 6.7890,
    change24h: 2.4,
    deviation: 0.14,
    activeSources: 9,
    totalSources: 12,
    lastUpdate: new Date(Date.now() - 6500),
    sources: [],
    confidence: 88,
  },
  {
    token: "SUI",
    price: 1.8901,
    change24h: 4.2,
    deviation: 0.17,
    activeSources: 8,
    totalSources: 12,
    lastUpdate: new Date(Date.now() - 7500),
    sources: [],
    confidence: 87,
  },
  {
    token: "APT",
    price: 9.8765,
    change24h: 3.5,
    deviation: 0.15,
    activeSources: 8,
    totalSources: 12,
    lastUpdate: new Date(Date.now() - 8500),
    sources: [],
    confidence: 86,
  },
  {
    token: "NEAR",
    price: 4.5678,
    change24h: 1.9,
    deviation: 0.13,
    activeSources: 9,
    totalSources: 12,
    lastUpdate: new Date(Date.now() - 5000),
    sources: [],
    confidence: 89,
  },
  {
    token: "ATOM",
    price: 12.3456,
    change24h: 0.7,
    deviation: 0.11,
    activeSources: 10,
    totalSources: 12,
    lastUpdate: new Date(Date.now() - 4000),
    sources: [],
    confidence: 91,
  },
  {
    token: "TRX",
    price: 0.1234,
    change24h: -0.3,
    deviation: 0.14,
    activeSources: 9,
    totalSources: 12,
    lastUpdate: new Date(Date.now() - 6000),
    sources: [],
    confidence: 88,
  },
  {
    token: "XLM",
    price: 0.1456,
    change24h: 1.1,
    deviation: 0.12,
    activeSources: 9,
    totalSources: 12,
    lastUpdate: new Date(Date.now() - 7000),
    sources: [],
    confidence: 89,
  },
];

export const mockChainData: ChainObserverData[] = [
  {
    chainName: "Solana",
    isHealthy: true,
    currentBlock: 285234123,
    gasPrice: "0.000005 SOL",
    tps: 3456,
    latency: 45,
    lastUpdate: new Date(),
  },
  {
    chainName: "Ethereum",
    isHealthy: true,
    currentBlock: 18934567,
    gasPrice: "23 Gwei",
    tps: 15,
    latency: 150,
    lastUpdate: new Date(),
  },
  {
    chainName: "Polygon",
    isHealthy: true,
    currentBlock: 52123789,
    gasPrice: "35 Gwei",
    tps: 145,
    latency: 100,
    lastUpdate: new Date(),
  },
  {
    chainName: "Arbitrum",
    isHealthy: true,
    currentBlock: 156789234,
    gasPrice: "0.1 Gwei",
    tps: 450,
    latency: 85,
    lastUpdate: new Date(),
  },
  {
    chainName: "Base",
    isHealthy: true,
    currentBlock: 89456123,
    gasPrice: "0.5 Gwei",
    tps: 234,
    latency: 120,
    lastUpdate: new Date(),
  },
  {
    chainName: "Radix",
    isHealthy: true,
    currentBlock: 12345678,
    gasPrice: "0.01 XRD",
    tps: 567,
    latency: 60,
    lastUpdate: new Date(),
  },
  {
    chainName: "Avalanche",
    isHealthy: true,
    currentBlock: 45678901,
    gasPrice: "25 nAVAX",
    tps: 4500,
    latency: 55,
    lastUpdate: new Date(),
  },
  {
    chainName: "Optimism",
    isHealthy: true,
    currentBlock: 98765432,
    gasPrice: "0.2 Gwei",
    tps: 320,
    latency: 95,
    lastUpdate: new Date(),
  },
  {
    chainName: "Fantom",
    isHealthy: true,
    currentBlock: 76543210,
    gasPrice: "120 Gwei",
    tps: 200,
    latency: 110,
    lastUpdate: new Date(),
  },
  {
    chainName: "BNBChain",
    isHealthy: true,
    currentBlock: 34567890,
    gasPrice: "5 Gwei",
    tps: 178,
    latency: 140,
    lastUpdate: new Date(),
  },
  {
    chainName: "Bitcoin",
    isHealthy: true,
    currentBlock: 820145,
    gasPrice: "15 sat/vB",
    tps: 7,
    latency: 600,
    lastUpdate: new Date(),
  },
  {
    chainName: "Cardano",
    isHealthy: true,
    currentBlock: 9876543,
    gasPrice: "0.17 ADA",
    tps: 250,
    latency: 180,
    lastUpdate: new Date(),
  },
  {
    chainName: "Polkadot",
    isHealthy: true,
    currentBlock: 18765432,
    gasPrice: "0.01 DOT",
    tps: 1000,
    latency: 75,
    lastUpdate: new Date(),
  },
  {
    chainName: "Sui",
    isHealthy: true,
    currentBlock: 23456789,
    gasPrice: "1000 MIST",
    tps: 2850,
    latency: 50,
    lastUpdate: new Date(),
  },
  {
    chainName: "Aptos",
    isHealthy: true,
    currentBlock: 67890123,
    gasPrice: "100 Octas",
    tps: 3200,
    latency: 65,
    lastUpdate: new Date(),
  },
  {
    chainName: "NEAR",
    isHealthy: true,
    currentBlock: 112345678,
    gasPrice: "0.0001 NEAR",
    tps: 100,
    latency: 130,
    lastUpdate: new Date(),
  },
  {
    chainName: "Cosmos",
    isHealthy: true,
    currentBlock: 18234567,
    gasPrice: "0.025 ATOM",
    tps: 10,
    latency: 200,
    lastUpdate: new Date(),
  },
  {
    chainName: "TRON",
    isHealthy: true,
    currentBlock: 56789012,
    gasPrice: "280 Sun",
    tps: 2000,
    latency: 85,
    lastUpdate: new Date(),
  },
  {
    chainName: "Stellar",
    isHealthy: true,
    currentBlock: 48765432,
    gasPrice: "100 Stroops",
    tps: 1000,
    latency: 105,
    lastUpdate: new Date(),
  },
  {
    chainName: "Hashgraph",
    isHealthy: true,
    currentBlock: 61234567,
    gasPrice: "0.0001 HBAR",
    tps: 10000,
    latency: 35,
    lastUpdate: new Date(),
  },
];


