<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0</TargetFramework></PropertyGroup><ItemGroup><Compile Include="../../OASIS Architecture/NextGenSoftware.OASIS.API.Core/Objects/NFT/GeoNFTCollectionPolicy.cs" Link="GeoNFTCollectionPolicy.cs" /></ItemGroup></Project>